# Generated by Django 3.1.3 on 2020-11-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20201117_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_exceptionnel', models.CharField(max_length=200)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.trajet')),
            ],
        ),
    ]
