# Generated by Django 3.1.3 on 2020-11-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_prediction_prediciton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='prediciton',
            new_name='prediction',
        ),
    ]
